### ISSUE TITLE
Error: spawn convert ENOENT

### ISSUE THREAD

**Issue by harshitgupta** [mmahrous/multi-rest#3]
Hi,

I have the following code: (minimal version of read me file)

```
const restify = require('restify');
const Multi = require('multi-rest');
const uuidv4 = require('uuid/v4');

const server = restify.createServer();
server.use(restify.plugins.bodyParser());

const upload_disk = new Multi({
    driver: {
        type: 'local',
        path: "./uploads/"
    },
    filename: (name) => `${name}_${uuidv4()}`,
    filefields: {
        image: {
            type: 'picture',
            thumbnail: {
                width: 400,
                height: 300
            },
            required: false,
            extensions: ['png', 'jpg']
        }
    },
});

server.post('/v/1/file',
    upload_disk,
    (req, res) => res.send({
        success: true,
        files: req.files,
        message: "file uploaded :)"
    }));

server.listen(3010, () => console.log('%s listening at %s', server.name, server.url))
```

Whenever I try to upload an image, the app crashes and throws the following error:

```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn convert ENOENT
    at _errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

Request screen shot from postman:

<img width="751" alt="screen shot 2017-09-24 at 2 19 50 pm" src="https://user-images.githubusercontent.com/1644577/30785914-88f5265c-a133-11e7-8b29-c189e3a10787.png">

Please advice if I am missing something.

**Comment by mmahrous** [comment]
@harshitgupta  I deployed the same code on my machine and it is working with me can you send me what is your runtime environment windows or linux or mac and which version also the node and npm version?

**Comment by harshitgupta** [comment]
Thanks a lot for your quick response. I did some debugging by myself and realized that its an issue with imagemagick.

On my mac, I installed imagemagick using brew

`brew install imagemagick`

It seems to be working fine now.

Thanks a lot again.
