### ISSUE TITLE
TypeError: Cannot read property 'image' of undefined

### ISSUE THREAD

**Issue by sriharsha1235** [mmahrous/multi-rest#5]
By using the example code that you have given is throwing error.

TypeError: Cannot read property 'image' of undefined

**Comment by mmahrous** [comment]
Hello @sriharsha1235 can you share your config for multi-rest ex *new Multi(...)* I made a test before and I double checked now and it is working, share you config and node version plus the operating system and which version of multi-rest you are using.

**Comment by sriharsha1235** [comment]
Actually, Imagemagick library is missing on the server.

**Comment by sriharsha1235** [comment]
I'm able to get it run yesterday. But today again the issue arise again and also How can I add custom validations?

**Comment by sriharsha1235** [comment]
const restify = require('restify');
const Multi = require('multi-rest');
const uuid = require('uuid');

var server = restify.createServer();

var upload_disk = new Multi({
    driver: {
        type: 'local',
        path: "./uploads/"
    },
    filename: (name) => { // the extention will be added automaticlly 
        return uuid.v4();
    },
    filefields: {
        image: {
            type: 'picture',
            thumbnail: {
                width: 400,
                height: 300
            },
            required: false,
            extensions: ['png', 'jpg']
        }
    }
});

server.use(restify.plugins.acceptParser(server.acceptable));
server.use(restify.plugins.queryParser());
server.use(restify.plugins.bodyParser());

server.post('/upload', upload_disk ,function (req, res, next){
	res.send({success: true, files: req.files, message: "file uploaded :)"});
});

server.listen(3000, function() {
  console.log('%s listening at %s', server.name, server.url);
});

**Comment by mmahrous** [comment]
@sriharsha1235 why do you mean by custom validation also you need to install imagemagick on the server what is the server OS, also I tried your code and it is working here is an image from post man 
![image](https://user-images.githubusercontent.com/5109309/33606722-207eb5a8-d9c7-11e7-8519-e999fac64f67.png)

**Comment by sriharsha1235** [comment]
After imagemagick installation it is working. I'm using ubuntu OS. For me thumbnail is not getting created.

**Comment by mmahrous** [comment]
@sriharsha1235 I pushed a new update on npm can you try and see if it working or not I had problem with locking the packages, it is fixed now.
