### ISSUE TITLE
Folder is not created

### ISSUE THREAD

**Issue by shystruk** [mmahrous/multi-rest#6]
Hi there,

The folder is not created "uploads" and I got File object in req.files.file, File path is "/var/folders/82/3s2yq3zj77l3xn1xvy9pgfx40000gn/T/upload_6bcd336e42b32122a8ed682e52ab".
I use restify.

```javascript
var upload_disk = new Multi({
  driver: {
      type: 'local',
      path: "uploads/"
  },
  filename: (name) => {
      return uuid.v4();
  },
  filefields: {
      image: {
          type: 'file',
          thumbnail: {
              width: 400,
              height: 300
          },
          required: false,
          extensions: ['png', 'jpg']
      }
  }
});

server.post({ path: "photo", version }, upload_disk, this.savePhoto.bind(this))

savePhoto(req, res, next) {
    console.log('FILE: ', req.files.file)

    res.json(200, {})
    return next()
}
```

**Comment by mmahrous** [comment]
Hi Vasyl, 

Sorry for the late reply right, I'm gonna run your code and investigate the issue, but in order to do so Which version you used for restify?  and Which version of multi-rest you installed?

Thanks, 
MMahrous.

**Comment by mmahrous** [comment]
@shystruk I didn't receive any reply from you yet so I will close this issue, and kindly if you faced any problem again contact us 😀
